### ISSUE TITLE
Make Error src/match_fault.cpp:16:26: fatal error: cryptopp/hex.h: No such file or directory

### ISSUE THREAD

**Issue by anuxraw** [oxagast/ansvif#2]
I have a problem how to fix it ?

Error: 
> src/match_fault.cpp:16:26: fatal error: cryptopp/hex.h: No such file or directory
> compilation terminated.
> Makefile:681: recipe for target 'src/ansvif-match_fault.o' failed
> make: *** [src/ansvif-match_fault.o] Error 1

Photo:
https://image.ibb.co/m9ZigG/Screenshot_2017_10_02_23_41_37.png

**Comment by oxagast** [comment]
Since it's looking for libcryptopp and not libcrypto++ then it looks like you're on Fedora or Redhat or a like distribution.  Correct me if I'm wrong so I can spin up a VM and correct the OS detection code in the Makefile.  But it appears as if you have unresolved dependencies.

If you are under a Redhat/Fedora based system then try: `sudo dnf install libcryptopp-devel`.
If you're under a Debian based distro then this probably won't work since Debian calls the header crypto++/hex.h instead of cryptopp/hex.h like the Makefile generated on your system is looking for.

I would try making sure you have no unresolved dependencies first.  Make sure libcryptopp is installed on your system.  Remember it has to be the development headers package.

**Comment by oxagast** [comment]
This report is being marked as closed.  I believe it was because of unmet dependencies.
