### ISSUE TITLE
Can't build ansvif, 'fault_code was not declared in this scope'

### ISSUE THREAD

**Issue by thallosaurus** [oxagast/ansvif#5]
Hello, everytime when I want to build ansvif, I get `error: ‘fault_code’ was not declared in this scope
` when running `aclocal && autoconf && automake -a && ./configure --enable-syscalls && make`

Here is the full Bashlog:
https://pastebin.com/5DbEdnyC

uname -a: Linux mercury 4.17.0-kali3-amd64 #1 SMP Debian 4.17.17-1kali1 (2018-08-21) x86_64 GNU/Linux

**Comment by oxagast** [comment]
It appears that from your log -D__DEBIAN__ isn't being triggered for Kali which is intended to trigger a bunch of #ifdef's throughout the code telling it if its debian/redhat based, android, bsd, windows, whatever.  Not sure why, yet since I don't have a Kali install handy so give me some time to spin up a virtual machine and look into a fix for it.

**Comment by oxagast** [comment]
I've pushed a possible fix for Kali Linux.  Compiles and seems to work in my VM now, try to git pull a fresh copy and recompile.  I'm running Kali 2018.2 for reference.
